### ISSUE TITLE
How to create an account.key on windows?

### ISSUE THREAD

**Issue by clarkezone** [google/goacme#25]
I can't seem to make a valid account.key to make goacme work on windows.  If i use putty to generate a SSH-2 RSA key I get: account key: no block found in "C:\\Users\\james\\.config\\acme\\account.key"

The documentation doesn't explain how to create account.key.

**Comment by crhym3** [comment]
James, it needs to be in PEM format. I suspect putty generates it in a different format.

See `goacme help reg` for account registration. It can also generate an account key for you with `goacme reg -gen mailto:contact@example.org`.

Documentation does desire better though, I absolutely agree. Will work on that.

**Comment by clarkezone** [comment]
Great thx.. i'm good now
